### PR TITLE
Improve colors in merge `gt_merge_stack()`

### PR DESCRIPTION
**Pull request by mrcaseb**
Currently the colors argument is directly used in the html string that creates the merged and stacked cells. Since some R colornames are not known in html they won't work at all. See
``` r
dat <- tibble::tibble(
  a = c(1:4, NA),
  b = c(rep(90, 2), NA, 98, 99)
) 
dat
#> # A tibble: 5 x 2
#>       a     b
#>   <int> <dbl>
#> 1     1    90
#> 2     2    90
#> 3     3    NA
#> 4     4    98
#> 5    NA    99

gt::gt(dat) |> 
  gtExtras::gt_merge_stack(a, b, colors = c("red2", "black"))
```
grafik

This updated translates the colornames to hcl with scales. This allows non html colornames that are built-in to R. 
Above code will output this:
grafik

### CODE REVIEW

**Comment by mrcaseb** [comment]
Notes:

- There is no News file that I could update
- There are some R CMD Check notes that I could fix but I didn't want to change too much
- Also some failing tests (but I think not related to my changes)

**Comment by jthomasmock** [comment]
Hey @mrcaseb - thanks! The R Cmd Check notes are plentiful - got a bit of work to do on my end before CRAN 😉 

There was also an open request for dynamically setting the colors (ie by team), so I'll sit on this PR for a little bit.

**Comment by mrcaseb** [comment]
Sidenote:
@guga31bb wrote a helper function that creates a script to silence check notes on tidy evaluation. 

https://github.com/guga31bb/ngscleanR/blob/master/data-raw/generate_silence_eval_notes.R

You might want to use it.

**Review by jthomasmock — CHANGES_REQUESTED** [review]
Thanks @mrcaseb ! We've made some good progress on improving all the general errors internally but due to the large code-base change, there's quite the diff.

Do you mind re-submitting or adjusting the PR so that it only affects the `merge_and_stack.R` file? Should be g2g after that.

**Comment by mrcaseb** [comment]
@jthomasmock I have merged the current master into the PR. 

However, now all checks are failing because the remote repository for the non CRAN dependency webshot2 is missing.
Additionally I highly recommend switching to v2 of some r-lib actions. 
I can fix the above mentioned stuff but I am unsure how many changes you want in this PR. So I'll keep it as is for now and wait for your answer.

**Review by jthomasmock — APPROVED** [review]

**Pull request merged**
