### PR TITLE
Housekeeping Part 2: (╯°□°）╯︵ ┻━┻

### PR DESCRIPTION
**Pull request by ddsjoberg**
1. Removed all NOTES about undefined global variables in the R CMD Check. This required adding many many many `.data` references. 
2. Removed tidyverse dependency, so you will be able to go to CRAN when you're ready. Moved webshot2 dependency from Imports to Suggests.
3. Removed references to webshot pkg (and dependency from DESCRIPTION)
4. Added a package level documentation file with `usethis::use_package_doc()` and consolidated all roxygen2 `@import` calls to this documentation file.
5. Registered global variable `"."` in the package documentation file.
6. On my machine, I was getting an error in `R/fontawesome-icons.R` stemming from line `if(is.null(palette) && unique(int_x) >= 8)`. I updated it to `if(is.null(palette) && length(unique(int_x)) >= 8)`. Please confirm this is accurate.
7. Added documentation of parameters as needed, and deleted unused parameter documentation.
8. Reconciled different names in the title and vignette name in `plots-in-gt.Rmd` 

Outstanding Items:
1. The updates above take care of all NOTES from R CMD Checks except those arising from the use of internal gt functions accessed with `gt:::`. Before you submit to CRAN, you'll need to resolve this note. There are ways to conceal calls to other package's internal functions from CRAN. But if you get caught, the package will be rejected.
2. I see that you made some updates while I was also making updates. I'll need to resolve some merge conflicts before you review :)

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@jthomasmock The merge conflicts were easier to resolve than I thought they would be! This PR is ready for review! ٩(^ ᴗ ^)۶

**Comment by jthomasmock** [comment]
You are an absolute saint, hope you know that! 😭 

Reviewing, also wanted to confirm - are you ok being indicated as a contributor? 

I would definitely say that you have left your mark on the package to say the least.

**Review by jthomasmock — APPROVED** [review]
This is an absolutely massive help - didn't realize that `.data$var` would solve all those issues 🤯 

I've reviewed this morning, and all looks good from me. I'm going to merge, run some additional automated tests and confirmations.

**Comment by ddsjoberg** [comment]
You're a saint for writing such a beautiful pkg!! Happy to be listed as a contributor: that is so kind :)

One other thing that'll need to be taken care of before CRAN: webshot2. CRAN will allow you a weak dependency (aka a package in Suggests) that is not on CRAN, but it must be housed in a proper pkg repository (i.e. they do not allow for `Remotes: rstudio/webshot2` in the DESCRIPTION). 

There are two pretty straightforward options:
1. Add an R Universe repo for your jthomasmock GH account. You can then add webshot2 to your universe. You'll then add this line to the DESCRIPTION `Additional_repositories: https://jthomasmock .r-universe.dev` Here's what mine looks like https://ddsjoberg.r-universe.dev/ I use gtExtras in my bstfun pkg, so gtExtras is auto-added to my universe.
2. You can create a drat repo and add it there. Then add a corresponding `Additional_repositories:` line to DESCRIPTION.

**Comment by jthomasmock** [comment]
Thanks again, I've been meaning to setup a r-universe, so this is a great excuse 😄  

> There are ways to conceal calls to other package's internal functions from CRAN. But if you get caught, the package will be rejected.

One more question re: `gt:::` - I would prefer to stick with those as it's unfortunately a _lot_ of vendored code otherwise. I'm taking a shot at removing their use, but if you have any suggestions I'd love to hear it!

**Comment by jthomasmock** [comment]
Good to know - I was able to get it all vendored, but may revisit as it's quite a bit of code!!!

I've bumped to v3.0 in prep for hopefully a CRAN release _soon_. Added you as a ctr, thanks so much!

**Pull request merged**
