### PR TITLE
Housekeeping Part 3:   ┬─┬ノ(ಠ_ಠノ)

### PR DESCRIPTION
**Pull request by ddsjoberg**
Hey hey! Oy, another one!

This PR focuses on items needed for CRAN acceptance, e.g. details stipulated in the Writing R Extensions Manual and in https://github.com/DavisVaughan/extrachecks. First submission of a pkg is tricky! But once it's been accepted, subsequent submissions are much easier.
- Since you're using the `Autho@Rs:` tag in `DESCRIPTION`, you don't need the Author and Maintainer fields.
- References to other packages, e.g. gt, must be quoted using single quotes. From Writing R Extensions Manual
    > The mandatory ‘Title’ field should give a short description of the package. Some package listings may truncate the title to 65 characters. It should use title case (that is, use capitals for the principal words: tools::toTitleCase can help you with this), not use any markup, not have any continuation lines, and not end in a period (unless part of …). Do not repeat the package name: it is often used prefixed by the name. Refer to other packages and external software in single quotes, and to book titles (and similar) in double quotes.
- I added a second sentence to the package description (lifted from what you had written in the README). CRAN requires at least two sentences.
- I bumped the minimum version requirement for tidyr and dplyr to 1.0.0 as both package had some breaking changes when they went to v1.0.0.
- I ran `usethis::use_tidy_description()`, which puts all the fields in the DESCRIPTION file in a standard order. It also puts the package dependencies in alphabetical order.
- I ran the URL checked and updated two URLs in the README.

Outstanding task: every exported function needs to be reviewed to ensure it has both an `@examples` and `@return` tag.

### CODE REVIEW

**Comment by ddsjoberg** [comment]
I am surprised that the GH Actions is failing due to a failure to install webshot2. I sent the built package to CRAN's check system (results here https://win-builder.r-project.org/4Y0AUy7ovkhG/). The system was able to see that webshot2 to was available in the additional repository, but also didn't appear to install it for the checks. This is something that will need to be looked into further as it results in two errors on the CRAN check system. 

¯\_(ツ)_/¯

**Comment by jthomasmock** [comment]
It _did_ fail on the main branch as well - unsure why and will look into that later tomorrow.

Thanks for the additional review!

**Comment by jthomasmock** [comment]
OK I've abandoned the idea of `webshot2` for now and added a note that it can be used but is up to the user.

Looks like the package is building on Windows/Mac/Linux so the RCmdCheck action is succeeding, but pkgdown/auto-rebuild of docs is still failing due to a package dep issue?

```
* pkgdown: dependencies must be TRUE, FALSE, NA or a list of dependency types>
   in process [82](https://github.com/jthomasmock/gtExtras/runs/6012119091?check_suite_focus=true#step:5:82)22 
  -->
  <simpleError: Cannot install packages:
  * pkgdown: dependencies must be TRUE, FALSE, NA or a list of dependency types>
  
   Stack trace:
  
   12. (function (...)  ...
   13. base:::withCallingHandlers(cli_message = function(msg) { ...
   14. get("lockfile_create_internal", asNamespace("pak"))(...)
   15. prop$stop_for_solution_error()
   16. private$plan$stop_for_solve_error()
   17. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
   18. base:::stop("Cannot install packages:\n", msg, call. = FALSE)
   19. base:::.handleSimpleError(function (e)  ...
   20. h(simpleError(msg, call))
   21. base:::stop(e)
   22. (function (e)  ...
  
   x Cannot install packages:
  * pkgdown: dependencies must be TRUE, FALSE, NA or a list of dependency types 
  
  Execution halted
```

I don't see a specific package mentioned in that error... 😕 

Any ideas @ddsjoberg ?

**Comment by jthomasmock** [comment]
Gotcha, I had a suggestion from @mrcaseb to switch to v2 as it resolved some issues for them. I'll try it for v1 again and see if that helps. Thanks!

**Comment by mrcaseb** [comment]
Not sure why the installation fails in v2. I guess the package cache needs to be refreshed but if v1 doesn’t make problems it’s probably best to stick with it in the pkgdown action.

**Pull request merged**
